# sklearn.svc
sklearn.svm.SVC(C=1.0, kernel='rbf', degree=3, gamma='auto', coef0=0.0, shrinking=True, probability=False,tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1,decision_function_shape=None,random_state=None)

## 参数解释：

### C：C-SVC的惩罚参数C?默认值是1.0

C越大，相当于惩罚松弛变量，希望松弛变量接近0，即对误分类的惩罚增大，趋向于对训练集全分对的情况，这样对训练集测试时准确率很高，但泛化能力弱。C值小，对误分类的惩罚减小，允许容错，将他们当成噪声点，泛化能力较强。

### kernel ：核函数，默认是rbf，可以是‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’ 

* 0 – 线性：u'v
* 1 – 多项式：(gamma\*u'*v + coef0)^degree
* 2 – RBF函数：exp(-gamma\*|u-v|^2)   ***径向基函数 (Radial Basis Function 简称 RBF)***
* 3 –sigmoid：tanh(gamma\*u'*v + coef0)

### degree ：多项式poly函数的维度，默认是3，选择其他核函数时会被忽略。

### gamma ： ‘rbf’,‘poly’ 和‘sigmoid’的核函数参数。默认是’auto’，则会选择1/n_features

### coef0 ：核函数的常数项。对于‘poly’和 ‘sigmoid’有用。

### probability ：是否采用概率估计？.默认为False

### shrinking ：是否采用shrinking heuristic方法，默认为true

### tol ：停止训练的误差值大小，默认为1e-3

### cache_size ：核函数cache缓存大小，默认为200

### class_weight ：类别的权重，字典形式传递。设置第几类的参数C为weight*C(C-SVC中的C)

### verbose ：允许冗余输出？

### max_iter ：最大迭代次数。-1为无限制。

### decision_function_shape ：‘ovo’, ‘ovr’ or None, default=None3

### random_state ：数据洗牌时的种子值，int值

# 主要调节的参数有：C、kernel、degree、gamma、coef0。

In [64]:
# coding=utf-8
import numpy as np 
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import  metrics
from sklearn.svm import SVC
from utils import *

train=pd.read_csv("./pima.csv",header=None)
train_normal=(train-train.mean())/(train.max()-train.min())
train_normal[8]=train[8]

kf = KFold(n_splits=10, shuffle=True,random_state=np.random.randint(11))

def calc(clf):
    accuracy=0.0
    confusion=np.zeros([2,2])
    for train_index, test_index in kf.split(train_normal.index):
        X=train_normal.ix[train_index].drop(8,axis=1).values
        y=train_normal.ix[train_index][8].values
        clf.fit(X,y)
        X_test=train_normal.ix[test_index].drop(8,axis=1).values
        predicted = clf.predict(X_test)
        expected = train_normal.ix[test_index][8].values
        conf_tmp=metrics.confusion_matrix(expected, predicted)
        confusion+=conf_tmp
        accy_tmp=metrics.accuracy_score(expected, predicted)
        accuracy+=accy_tmp
    #     print conf_tmp
#         print accy_tmp
    print confusion
    print accuracy/10.0

In [33]:
# rbf kernel 
clf = SVC(C=1.6,gamma=0.6)
calc(clf)

[[ 448.   52.]
 [ 123.  145.]]
0.772146274778


In [13]:
# linear kernel
clf = SVC(C=1.5, kernel='linear' )
calc(clf)

[[ 449.   51.]
 [ 124.  144.]]
0.772163362953


In [26]:
# polynormial kernel
clf = SVC(C=1, kernel='poly',degree=3,gamma=0.9 ,coef0=2)
calc(clf)

[[ 444.   56.]
 [ 119.  149.]]
0.772112098428


In [71]:
# sigmoid kernel
    clf = SVC(C=1, kernel='sigmoid',gamma=0.5,coef0=0)
    calc(clf)

[[ 455.   45.]
 [ 130.  138.]]
0.772095010253
