In [5]:
# coding=utf-8
import numpy as np 
import pandas as pd
from sklearn.model_selection import KFold
from sklearn import  metrics
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

train=pd.read_csv("./pima.csv",header=None)
train_normal=(train-train.mean())/(train.max()-train.min())
train_normal[8]=train[8]

kf = KFold(n_splits=10, shuffle=True,random_state=np.random.randint(11))

def calc(clf):
    accuracy=0.0
    confusion=np.zeros([2,2])
    for train_index, test_index in kf.split(train_normal.index):
        X=train_normal.ix[train_index].drop(8,axis=1).values
        y=train_normal.ix[train_index][8].values
        clf.fit(X,y)
        X_test=train_normal.ix[test_index].drop(8,axis=1).values
        predicted = clf.predict(X_test)
        expected = train_normal.ix[test_index][8].values
        conf_tmp=metrics.confusion_matrix(expected, predicted)
        confusion+=conf_tmp
        accy_tmp=metrics.accuracy_score(expected, predicted)
        accuracy+=accy_tmp
    #     print conf_tmp
#         print accy_tmp
    print confusion
    print accuracy/10.0
print "ok"

ok


In [17]:
# clf = tree.DecisionTreeClassifier()
# calc(clf)
bdt = AdaBoostClassifier(tree.DecisionTreeClassifier(max_depth=6), algorithm="SAMME", n_estimators=100)
calc(bdt)

[[ 415.   85.]
 [ 110.  158.]]
0.746172248804


In [20]:
# multi layers neural network classifier
clf = MLPClassifier(alpha=1e-2, hidden_layer_sizes=(50), random_state=1)
calc(clf)

[[ 444.   56.]
 [ 116.  152.]]
0.776076555024


In [15]:
# decision tree classifier
clf = tree.DecisionTreeClassifier(max_depth=6)
calc(clf)

[[ 402.   98.]
 [ 120.  148.]]
0.716182501709


In [7]:
# random forrest classifier
clf = RandomForestClassifier(max_depth=7, n_estimators=20)
calc(clf)

[[ 437.   63.]
 [ 120.  148.]]
0.761722488038


In [5]:
# k- nearly neigbor
from sklearn.neighbors import NearestNeighbors
clf = NearestNeighbors(n_neighbors=1)
accuracy=0.0
confusion=np.zeros([2,2])
drop_arr=[8,2,3,4]

for train_index, test_index in kf.split(train_normal.index):
    X=train_normal.ix[train_index].drop(drop_arr,axis=1).values
    y=train_normal.ix[train_index][8].values
    clf.fit(X,y)
    X_test=train_normal.ix[test_index].drop(drop_arr,axis=1).values
    
    predicted = clf.kneighbors(X_test)
    index=np.array(predicted[1]).reshape(1,len(predicted[1]))[0]
    predicted=train_normal.ix[index][8].values
    
    expected = train_normal.ix[test_index][8].values
    conf_tmp=metrics.confusion_matrix(expected, predicted)
    confusion+=conf_tmp
    accy_tmp=metrics.accuracy_score(expected, predicted)
    accuracy+=accy_tmp
#     print conf_tmp
#     print accy_tmp
print confusion
print accuracy/10.0


[[ 330.  170.]
 [ 162.  106.]]
0.567754613807
